package com.vityarthi.dbms.ui;
import com.vityarthi.dbms.dao.*; import com.vityarthi.dbms.model.*; import com.vityarthi.dbms.service.ReportService; import com.vityarthi.dbms.util.InputValidator; import java.sql.SQLException; import java.util.*;
public class ConsoleUI {
 private final Scanner in=new Scanner(System.in); private final StudentDAO students=new StudentDAO(); private final CourseDAO courses=new CourseDAO(); private final EnrollmentDAO enrollments=new EnrollmentDAO(); private final ReportService reports=new ReportService();
 public void start(){System.out.println("=== VITyarthi Student Database Management System ==="); while(true){try{menu();int c=readInt("Choice: ");switch(c){case 1->addStudent();case 2->listStudents();case 3->updateStudent();case 4->deleteStudent();case 5->listCourses();case 6->addCourse();case 7->enroll();case 8->studentEnrollments();case 9->grade();case 10->reports();case 0->{System.out.println("Exiting.");return;}default->System.out.println("Invalid choice.");}}catch(Exception e){System.out.println("Operation failed: "+e.getMessage());}}}
 private void menu(){System.out.println("\n1 Add Student\n2 List Students\n3 Update Student\n4 Delete Student\n5 List Courses\n6 Add Course\n7 Enroll Student\n8 View Student Courses\n9 Set Grade\n10 Reports\n0 Exit");}
 private void addStudent()throws SQLException{String r=read("Roll No: "),n=read("Name: "),e=read("Email: "),d=read("Department: ");int s=readInt("Semester: ");InputValidator.required(r,"Roll No");InputValidator.required(n,"Name");InputValidator.semester(s);students.add(new Student(0,r,n,e,d,s));System.out.println("Student added.");}
 private void listStudents()throws SQLException{System.out.printf("%-4s %-15s %-22s %-30s %-18s %-4s%n","ID","ROLL","NAME","EMAIL","DEPARTMENT","SEM");for(Student s:students.findAll())System.out.printf("%-4d %-15s %-22s %-30s %-18s %-4d%n",s.id(),s.rollNo(),s.name(),s.email(),s.department(),s.semester());}
 private void updateStudent()throws SQLException{int id=readInt("Student ID: ");var old=students.findById(id);if(old.isEmpty()){System.out.println("Not found.");return;}Student x=old.get();String r=read("Roll No ["+x.rollNo()+"]: ");String n=read("Name ["+x.name()+"]: ");String e=read("Email ["+x.email()+"]: ");String d=read("Department ["+x.department()+"]: ");String ss=read("Semester ["+x.semester()+"]: ");Student y=new Student(id,r.isBlank()?x.rollNo():r,n.isBlank()?x.name():n,e.isBlank()?x.email():e,d.isBlank()?x.department():d,ss.isBlank()?x.semester():Integer.parseInt(ss));InputValidator.semester(y.semester());students.update(y);System.out.println("Student updated.");}
 private void deleteStudent()throws SQLException{int id=readInt("Student ID: ");System.out.println(students.delete(id)?"Student deleted.":"Student not found.");}
 private void listCourses()throws SQLException{System.out.printf("%-4s %-12s %-35s %-7s%n","ID","CODE","COURSE","CREDITS");for(Course c:courses.findAll())System.out.printf("%-4d %-12s %-35s %-7d%n",c.id(),c.code(),c.name(),c.credits());}
 private void addCourse()throws SQLException{String code=read("Code: "),name=read("Name: ");int cr=readInt("Credits: ");courses.add(new Course(0,code,name,cr));System.out.println("Course added.");}
 private void enroll()throws SQLException{int sid=readInt("Student ID: "),cid=readInt("Course ID: ");enrollments.enroll(sid,cid);System.out.println("Enrollment created.");}
 private void studentEnrollments()throws SQLException{enrollments.printStudentEnrollments(readInt("Student ID: "));}
 private void grade()throws SQLException{int id=readInt("Enrollment ID: ");enrollments.setGrade(id,read("Grade: "));System.out.println("Grade updated.");}
 private void reports()throws SQLException{reports.dashboard();reports.departmentReport();}
 private String read(String p){System.out.print(p);return in.nextLine().trim();} private int readInt(String p){while(true)try{return Integer.parseInt(read(p));}catch(NumberFormatException e){System.out.println("Enter a valid number.");}}
}
